<a href="https://colab.research.google.com/github/Andrei-web-front/Andrei-web-front/blob/main/%D0%A0%D0%B0%D1%81%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5_%D0%BC%D0%B5%D0%B6%D0%B4%D1%83_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%B0%D0%BC%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def floyd_warshall(graph):
    num_vertices = len(graph)
    dist = np.array(graph)

    for k in range(num_vertices):
        for i in range(num_vertices):
            for j in range(num_vertices):
                if dist[i][k] + dist[k][j] < dist[i][j]:
                    dist[i][j] = dist[i][k] + dist[k][j]

    return dist

# Пример использования
graph = [
    [0, 3, float('inf'), 5],
    [2, 0, float('inf'), 4],
    [float('inf'), 1, 0, float('inf')],
    [float('inf'), float('inf'), 2, 0]
]

shortest_paths = floyd_warshall(graph)
print(shortest_paths)

[[0. 3. 7. 5.]
 [2. 0. 6. 4.]
 [3. 1. 0. 5.]
 [5. 3. 2. 0.]]


In [2]:
import numpy as np

# Названия городов
cities = ["МСК", "СПБ", "КЗН", "ЕКБ", "НВС", "РНД", "ВЛД", "СОЧ", "КГД", "КРД"]

# Матрица расстояний (в км)
graph = np.array([
    [0,    700,  800,  1800, 3300, 1100, 9200, 1600, 1250, 1350],
    [700,  0,    1500, 2500, 3800, 1900, 9900, 2300, 800,  2200],
    [800,  1500, 0,    900,  2500, 1400, 8400, 1900, 2000, 1600],
    [1800, 2500, 900,  0,    1600, 2100, 7500, 2800, 2900, 2400],
    [3300, 3800, 2500, 1600, 0,    3700, 5900, 4400, 4500, 4000],
    [1100, 1900, 1400, 2100, 3700, 0,    10100, 500,  2350, 300],
    [9200, 9900, 8400, 7500, 5900, 10100, 0,    10600, 10450, 10400],
    [1600, 2300, 1900, 2800, 4400, 500,  10600, 0,    2850, 350],
    [1250, 800,  2000, 2900, 4500, 2350, 10450, 2850, 0,    2600],
    [1350, 2200, 1600, 2400, 4000, 300,  10400, 350,  2600, 0]
])

# Алгоритм Флойда — Уоршелла
def floyd_warshall(graph):
    n = len(graph)
    dist = graph.copy()
    for k in range(n):
        for i in range(n):
            for j in range(n):
                if dist[i][k] + dist[k][j] < dist[i][j]:
                    dist[i][j] = dist[i][k] + dist[k][j]
    return dist

shortest_paths = floyd_warshall(graph)

# Вывод результатов
print("Кратчайшие расстояния между городами (км):\n")
for i in range(len(cities)):
    for j in range(len(cities)):
        if i != j:
            print(f"{cities[i]} → {cities[j]}: {shortest_paths[i][j]} км")
        else:
            print(f"{cities[i]} → {cities[j]}: 0 км")

Кратчайшие расстояния между городами (км):

МСК → МСК: 0 км
МСК → СПБ: 700 км
МСК → КЗН: 800 км
МСК → ЕКБ: 1700 км
МСК → НВС: 3300 км
МСК → РНД: 1100 км
МСК → ВЛД: 9200 км
МСК → СОЧ: 1600 км
МСК → КГД: 1250 км
МСК → КРД: 1350 км
СПБ → МСК: 700 км
СПБ → СПБ: 0 км
СПБ → КЗН: 1500 км
СПБ → ЕКБ: 2400 км
СПБ → НВС: 3800 км
СПБ → РНД: 1800 км
СПБ → ВЛД: 9700 км
СПБ → СОЧ: 2300 км
СПБ → КГД: 800 км
СПБ → КРД: 2050 км
КЗН → МСК: 800 км
КЗН → СПБ: 1500 км
КЗН → КЗН: 0 км
КЗН → ЕКБ: 900 км
КЗН → НВС: 2500 км
КЗН → РНД: 1400 км
КЗН → ВЛД: 8400 км
КЗН → СОЧ: 1900 км
КЗН → КГД: 2000 км
КЗН → КРД: 1600 км
ЕКБ → МСК: 1700 км
ЕКБ → СПБ: 2400 км
ЕКБ → КЗН: 900 км
ЕКБ → ЕКБ: 0 км
ЕКБ → НВС: 1600 км
ЕКБ → РНД: 2100 км
ЕКБ → ВЛД: 7500 км
ЕКБ → СОЧ: 2600 км
ЕКБ → КГД: 2900 км
ЕКБ → КРД: 2400 км
НВС → МСК: 3300 км
НВС → СПБ: 3800 км
НВС → КЗН: 2500 км
НВС → ЕКБ: 1600 км
НВС → НВС: 0 км
НВС → РНД: 3700 км
НВС → ВЛД: 5900 км
НВС → СОЧ: 4200 км
НВС → КГД: 4500 км
НВС → КРД: 4000 км
РНД → МСК: 1100 км
РНД → СПБ